name: "Build Extension .zip" # i cate hrx

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps: # is ts the formatting?
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip extension # dont zip .github because .github no cool
        run: |
          zip -rq spicetown-use-this.zip . \
          -x "spicetown-use-this.zip" \
          -x "*.git*" \
          -x "*.github*" \
          -x "README.md" \
          -x "LICENSE" \
          -x ".gitignore"
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with: 
          name: spicetown-unzip-this
          path: spicetown-use-this.zip
          retention-days: 5
          if-no-files-found: error